### PR TITLE
Support PHP 7.1 with bumping xdebug version

### PR DESCRIPTION
**Pull request by oxyc**
See https://github.com/oerdnj/deb.sury.org/issues/496.

I also reverted your merge as it wasn't actually doing any good.

### CODE REVIEW

**Comment by oxyc** [comment]
See #37.

**Comment by oxyc** [comment]
Running a local test to see if this works on 7.1.

**Comment by geerlingguy** [comment]
I think I'm getting a bit ahead of myself here, eek! But using the latest version is good regardless.

**Comment by geerlingguy** [comment]
Tagged 2.2.2 to default to latest version, will add that role version to Drupal VM in a few min.

**Comment by oxyc** [comment]
```
vagrant@drupalvm-php:~$ php --version
PHP 7.1.0-3+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0-3+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by geerlingguy** [comment]
Woot!

**Comment by TryingToFindALoginWhichIsNotRegistered** [comment]
On debian 10 (Buster) php-xdebug installs a lot of php7.0 (like cli etc.). But I've already php7.1-cli installed and don't want to have multiple versions. If I install php-xdebug and after that I delete 7.0 and 5.6 stuff, does it lead to problems, If all depencies in 7.0 are installed in 7.1?

**Pull request merged**
