### PR TITLE
Added php_xdebug_config_dirs to setup apache, fpm & cli on Debian.

### PR DESCRIPTION
**Pull request by thom8**
Similar config to the xhprof role - https://github.com/geerlingguy/ansible-role-php-xhprofSimilar config to the xhprof role - https://github.com/geerlingguy/ansible-role-php-xhprof

### CODE REVIEW

**Comment by thom8** [comment]
Also fixed up the tests by creating the default apache directory on 12.04 & 14.04

**Comment by alexdesignworks** [comment]
@thom8 Thank for doing this. Really critical as all of our boxes require additional setup steps.

@geerlingguy  Any chance to look at this as a priority please

**Comment by thom8** [comment]
@geerlingguy xdebug cli support on Drupal VM using `geerlingguy/ubuntu1404` will likely be broken as it currently only creates `xdebug.ini` for `apache2`, `fpm` or `cli`.

This PR will create `xdebug.ini` for `apache2`, `fpm` and `cli`.

**Comment by oxyc** [comment]
The xhprof role also makes sure the conf directories exist: https://github.com/geerlingguy/ansible-role-php-xhprof/blob/master/tasks/configure.yml#L2:L8

Otherwise I believe the task fails when either `apache2` or `fpm` isnt installed.

**Comment by thom8** [comment]
@oxyc added the task, this could eventually be pushed back to the geerlingguy.php role as that is a dependancy of both and these roles could just use a shared `php_config_dirs ` var.

**Comment by oxyc** [comment]
Would make life a bit easier yes. Although over at geerlingguy.php it only configures `php.ini` for the configured webserver, all other conf directories are left untouched. This was by design as I think the `php.ini` should be different between webserver and cli. That's debatable though :)

**Comment by thom8** [comment]
Yeah, that's another issue I've run into, would be fair assumption to make them all the same by default as you can override `php_config_dirs` and run the role multiple times with different config.

**Comment by geerlingguy** [comment]
@thom8 - I'm waiting on test results from @oxyc's upstream PR above. If all is well, I'll go that route, then we can change this role to assume the PHP role is creating those dirs correctly, then use the same/new `php_conf_paths` var.

**Comment by thom8** [comment]
Perfect :+1: 

Rerolled the PR based on the `php_conf_paths` var -- will retest when this is merged.

**Comment by thom8** [comment]
https://github.com/geerlingguy/ansible-role-php/pull/89 has been merged can a release be created for php role to allow this PR to be merged?

**Comment by geerlingguy** [comment]
Oops! Forgot to make a new release after merging that PR. I will finish a little extra testing, cut a new release, then we can retest this PR and make sure it works with the upstream changes.

**Pull request merged**
